artifact_location: file:///home/wiktor/code/deepdrivepl-klasyfikacja/modul-4/mlflow_logs/931554227705327702
creation_time: 1691234470458
experiment_id: '931554227705327702'
last_update_time: 1691234470458
lifecycle_stage: active
name: modul-3-zadanie-domowe
