artifact_location: file:///c:/Users/Wiktor/code/kurs-klasyfikacja/modul-4/mlflow_logs/312211085865713083
creation_time: 1690966538267
experiment_id: '312211085865713083'
last_update_time: 1691234467672
lifecycle_stage: deleted
name: modul-3-zadanie-domowe
tags: {}
