artifact_location: file:///c:/Users/Wiktor/code/kurs-klasyfikacja/modul-4/mlflow_logs/0
creation_time: 1690966508943
experiment_id: '0'
last_update_time: 1690966508943
lifecycle_stage: active
name: Default
